import { CalculationType } from "./enum/CalculationType"
import type { StatisticProperty } from "./StatisticProperty"

export const BattingProperties: StatisticProperty[] = [
    {
        abbreviation: "avg",
        name: "Batting Average",
        type: CalculationType.AVG,
        alias: "ba",
        wiki: "https://en.wikipedia.org/wiki/Batting_average_(baseball)",
    },
    {
        abbreviation: "g",
        name: "Games Played",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Games_played",
    },
    {
        abbreviation: "pa",
        name: "Plate Appearances",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Plate_appearance",
    },
    {
        abbreviation: "ab",
        name: "At Bats",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/At_bat",
    },
    {
        abbreviation: "r",
        name: "Runs",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Run_(baseball)",
    },
    {
        abbreviation: "h",
        name: "Hits",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Hit_(baseball)",
    },
    {
        abbreviation: "2b",
        name: "Doubles",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Double_(baseball)",
    },
    {
        abbreviation: "3b",
        name: "Triples",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Triple_(baseball)",
    },
    {
        abbreviation: "hr",
        name: "Home Runs",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Home_run",
    },
    {
        abbreviation: "rbi",
        name: "Runs Batted In",
        wiki: "https://en.wikipedia.org/wiki/Run_batted_in",
        type: CalculationType.SUM,
    },
    {
        abbreviation: "sh",
        name: "Sacrifice Hits",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Sacrifice_hit",
    },
    {
        abbreviation: "sf",
        name: "Sacrifice Flies",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Sacrifice_fly",
    },
    {
        abbreviation: "hbp",
        name: "Hit by Pitches",
        alias: "hb",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Hit_by_pitch",
    },
    {
        abbreviation: "bb",
        name: "Base on Balls",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Base_on_balls",
    },
    {
        abbreviation: "ibb",
        name: "Intentional Base on Balls",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Intentional_base_on_balls",
    },
    {
        abbreviation: "k",
        name: "Strikeout",
        alias: "so",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Strikeout",
    },
    {
        abbreviation: "sb",
        name: "Stolen Bases",
        wiki: "https://en.wikipedia.org/wiki/Stolen_base",
        type: CalculationType.SUM,
    },
    {
        abbreviation: "cs",
        name: "Caught Stealing",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Caught_stealing",
    },
    {
        abbreviation: "gdp",
        name: "Grounded into Double Plays",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Double_play",
    },
    {
        abbreviation: "slg",
        name: "Slugging percentage",
        type: CalculationType.AVG,
        wiki: "https://en.wikipedia.org/wiki/Slugging_percentage",
    },
    {
        abbreviation: "obp",
        name: "On-Base Percentage",
        type: CalculationType.AVG,
        wiki: "https://en.wikipedia.org/wiki/On-base_percentage",
    },
    {
        abbreviation: "ops",
        name: "On-Base plus Slugging",
        type: CalculationType.AVG,
        wiki: "https://en.wikipedia.org/wiki/On-base_plus_slugging",
    },
]
