import { CalculationType } from "./enum/CalculationType"
import type { StatisticProperty } from "./StatisticProperty"

export const PitchingProperties: StatisticProperty[] = [
    {
        abbreviation: "w",
        name: "Wins",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Win_(baseball)",
    },
    {
        abbreviation: "l",
        name: "Losses",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Loss_(baseball)",
    },
    {
        abbreviation: "era",
        name: "Earned Run Average",
        type: CalculationType.AVG,
        wiki: "https://en.wikipedia.org/wiki/Earned_run_average",
    },
    {
        abbreviation: "g",
        name: "Games pitched",
        type: CalculationType.SUM,
        alias: "app",
        wiki: "https://en.wikipedia.org/wiki/Games_pitched",
    },
    {
        abbreviation: "gs",
        name: "Games Started",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Games_started",
    },
    {
        abbreviation: "cg",
        name: "Complete Games",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Complete_game",
    },
    {
        abbreviation: "sho",
        name: "Shutouts",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Shutout_(baseball)",
    },
    {
        abbreviation: "sv",
        name: "Saves",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Save_(baseball)",
    },
    {
        abbreviation: "ip",
        name: "Innings Pitched",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Innings_pitched",
    },
    {
        abbreviation: "r",
        name: "Runs allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Run_(baseball)",
    },
    {
        abbreviation: "er",
        name: "Earned Runs",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Earned_run",
    },
    {
        abbreviation: "h",
        name: "Hits allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Hits_allowed",
    },
    {
        abbreviation: "2b",
        name: "Doubles allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Double_(baseball)",
    },
    {
        abbreviation: "3b",
        name: "Triples allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Triple_(baseball)",
    },
    {
        abbreviation: "hr",
        name: "Home Runs allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Home_runs_allowed",
    },
    {
        abbreviation: "sh",
        name: "Sacrifice Hits allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Sacrifice_hit",
    },
    {
        abbreviation: "sf",
        name: "Sacrifice Flies allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Sacrifice_fly",
    },
    {
        abbreviation: "hbp",
        name: "Hit Batsmen",
        alias: "hb",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Hit_by_pitch",
    },
    {
        abbreviation: "bb",
        name: "Base on Balls allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Base_on_balls",
    },
    {
        abbreviation: "ibb",
        name: "Intentional Base on Balls allowed",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Intentional_base_on_balls",
    },
    {
        abbreviation: "so",
        alias: "k",
        name: "Strikeouts",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Strikeout",
    },
    {
        abbreviation: "wp",
        name: "Wild Pitches",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Wild_pitch",
    },
    {
        abbreviation: "bk",
        name: "Balks",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Balk",
    },
    {
        abbreviation: "ab",
        name: "Batters faced",
        type: CalculationType.SUM,
        wiki: "https://en.wikipedia.org/wiki/Batters_faced",
    },
    {
        abbreviation: "bavg",
        name: "Opponents Batting Average",
        type: CalculationType.AVG,
        wiki: "https://en.wikipedia.org/wiki/Opponents_batting_average",
    },
]
